# Run with treefmt --allow-missing-formatter.

[global]
excludes = [
  "go.sum",
  "go.mod",
  "**/.gitignore",
  "assets/**",
  "dist/**",
]

[formatter.gofumpt]
command = "gofumpt"
options = ["-w"]
includes = ["*.go"]

[formatter.gci]
command = "gci"
options = ["write", "--skip-generated"]
includes = ["*.go"]
priority = 1

[formatter.markdownlint]
command = "markdownlint"
options = ["--fix"]
includes = ["*.md"]

[formatter.prettier]
command = "prettier"
options = ["-w"]
includes = ["*.md"]
priority = 1
