# Run with treefmt --allow-missing-formatter.

[global]
excludes = [
  "go.sum",
  "go.mod",
  "**/.gitignore",
  "assets/images/**",
  "assets/audio/**",
  "dist/**",
]

[formatter.gofumpt]
command = "gofumpt"
options = ["-w"]
includes = ["*.go"]

[formatter.gci]
command = "gci"
options = ["write", "--skip-generated"]
includes = ["*.go"]
priority = 1
